theme: jekyll-theme-leap-day
title: Econometría Financiera en Python para el ITM
description: Aqui se recabará el codigo para la enseñanza de la materia Econometría Financiera para Ingeneria Financiera en Python
